//* This file was NOT generated by SquareLine Studio
// Make sure "Call functions export file" option is set to "dont't export" else this will be overwritten

#include <Arduino.h>
#include "ui.h"
#include "time_func.h"

void logoPressed(lv_event_t *e)
{
	Serial.println("Logo pressed");
	backlightToggle();
}
